server:
    port: 8080

spring:
    datasource:
        username: system
        password: system
        url: jdbc:oracle:thin:@localhost:1521:xe
    application:
        name: jcopy
        version: 1
